#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#./Allmesh

runApplication decomposePar -allRegions

printf "\n%s\n" "Creating files for paraview post-processing"
paraFoam -touchAll
echo

runParallel $(getApplication)

runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
