#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

#runApplication foamSetupCHT

runApplication -s solid foamDictionary -entry internalField -set "uniform 298" 0/solid/T
#runApplication -s fluid foamDictionary -entry boundaryField.inlet -set "uniform 1073" 0/fluid/T

runApplication decomposePar -allRegions

printf "\n%s\n" "Creating files for paraview post-processing"
paraFoam -touchAll
echo

runParallel $(getApplication)

runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
