#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
#runApplication transformPoints "scale=(0.1 0.1 0.1)"
runApplication splitMeshRegions -cellZones -overwrite -defaultRegionName fluid 
runApplication foamSetupCHT

runApplication -s solid foamDictionary -entry internalField -set "uniform 298" 0/solid/T
#------------------------------------------------------------------------------
